{
 "title": "TAE Mpool Allocator",
 "panels": [
  {
   "title": "TAE DEFAULT",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_mem_mpool_allocated_size{type=\"tae_default\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_default"
    },
    {
     "expr": "sum(mo_mem_mpool_high_water_mark_size{type=\"tae_default_high_water_mark\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_default_high_water_mark"
    }
   ]
  },
  {
   "title": "TAE MUTABLE",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_mem_mpool_allocated_size{type=\"tae_mutable\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_mutable"
    },
    {
     "expr": "sum(mo_mem_mpool_high_water_mark_size{type=\"tae_mutable_high_water_mark\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_mutable_high_water_mark"
    }
   ]
  },
  {
   "title": "TAE SMALL",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_mem_mpool_allocated_size{type=\"tae_small\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_small"
    },
    {
     "expr": "sum(mo_mem_mpool_high_water_mark_size{type=\"tae_small_high_water_mark\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_small_high_water_mark"
    }
   ]
  },
  {
   "title": "VECTORPOOL DEFAULT",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_mem_mpool_allocated_size{type=\"vectorpool_default\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "vectorpool_default"
    },
    {
     "expr": "sum(mo_mem_mpool_high_water_mark_size{type=\"vectorpool_default_high_water_mark\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "vectorpool_default_high_water_mark"
    }
   ]
  },
  {
   "title": "TAE LOGTAIL",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_mem_mpool_allocated_size{type=\"tae_logtail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_logtail"
    },
    {
     "expr": "sum(mo_mem_mpool_high_water_mark_size{type=\"tae_logtail_high_water_mark\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_logtail_high_water_mark"
    }
   ]
  },
  {
   "title": "TAE CHECKPOINT",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_mem_mpool_allocated_size{type=\"tae_checkpoint\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_checkpoint"
    },
    {
     "expr": "sum(mo_mem_mpool_high_water_mark_size{type=\"tae_checkpoint_high_water_mark\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_checkpoint_high_water_mark"
    }
   ]
  },
  {
   "title": "TAE MERGE",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_mem_mpool_allocated_size{type=\"tae_merge\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_merge"
    },
    {
     "expr": "sum(mo_mem_mpool_high_water_mark_size{type=\"tae_merge_high_water_mark\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_merge_high_water_mark"
    }
   ]
  },
  {
   "title": "TAE WORKSPACE",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_mem_mpool_allocated_size{type=\"tae_workspace\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_workspace"
    },
    {
     "expr": "sum(mo_mem_mpool_high_water_mark_size{type=\"tae_workspace_high_water_mark\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_workspace_high_water_mark"
    }
   ]
  },
  {
   "title": "TAE DEBUG",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_mem_mpool_allocated_size{type=\"tae_debug\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_debug"
    },
    {
     "expr": "sum(mo_mem_mpool_high_water_mark_size{type=\"tae_debug_high_water_mark\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "tae_debug_high_water_mark"
    }
   ]
  },
  {
   "title": "GLOBAL STATS ALLOCATED",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_mem_mpool_allocated_size{type=\"global_stats_allocated\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "global_stats_allocated"
    },
    {
     "expr": "sum(mo_mem_mpool_high_water_mark_size{type=\"global_stats_allocated_high_water_mark\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "global_stats_allocated_high_water_mark"
    }
   ]
  },
  {
   "title": "Cross Pool Free Counter",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mo_mem_cross_pool_free_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])"
    }
   ]
  }
 ]
}