{
 "title": "Flush Table Tail",
 "panels": [
  {
   "title": "Flush table tail Count",
   "type": "timeseries",
   "targets": [
    {
     "expr": "increase(mo_task_short_duration_seconds_count{type=\"flush_table_tail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Flush table tail Duration",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"flush_table_tail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"flush_table_tail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"flush_table_tail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"flush_table_tail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}
{
 "title": "Merge",
 "panels": [
  {
   "title": "Merge Count",
   "type": "timeseries",
   "targets": [
    {
     "expr": "increase(mo_task_execute_results_total{type=\"merged_block\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "Block Count"
    },
    {
     "expr": "increase(mo_task_scheduled_by_total{type=\"merge\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "Schedule Count"
    }
   ]
  },
  {
   "title": "Merge Batch Size",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(mo_task_execute_results_total{type=\"merged_size\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "Size"
    }
   ]
  }
 ]
}
{
 "title": "Checkpoint",
 "panels": [
  {
   "title": "Checkpoint Entry Pending",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_long_duration_seconds_bucket{type=\"ckp_entry_pending\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_long_duration_seconds_bucket{type=\"ckp_entry_pending\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_long_duration_seconds_bucket{type=\"ckp_entry_pending\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_long_duration_seconds_bucket{type=\"ckp_entry_pending\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "ICheckpoint Collecting Duration",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"ickp_collect_uage\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"ickp_collect_uage\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"ickp_collect_uage\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"ickp_collect_uage\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Checkpoint Load Object Count",
   "type": "timeseries",
   "targets": [
    {
     "expr": "increase(mo_task_execute_results_total{type=\"gckp_load_object\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "GCheckpoint"
    },
    {
     "expr": "increase(mo_task_execute_results_total{type=\"ickp_load_object\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "ICheckpoint"
    }
   ]
  },
  {
   "title": "GCheckpoint Collecting Duration",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"gckp_collect_uage\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"gckp_collect_uage\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"gckp_collect_uage\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"gckp_collect_uage\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}
{
 "title": "Read Selectivity",
 "panels": [
  {
   "title": "Read filter rate",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(mo_task_selectivity{type=\"readfilter_hit\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod) / on(pod) sum(mo_task_selectivity{type=\"readfilter_total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "filterout-{{ pod }}"
    }
   ]
  },
  {
   "title": "Block range filter rate",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(mo_task_selectivity{type=\"block_hit\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod) / on(pod) sum(mo_task_selectivity{type=\"block_total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "filterout-{{ pod }}"
    }
   ]
  },
  {
   "title": "Column update filter rate",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(mo_task_selectivity{type=\"column_hit\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod) / on(pod) sum(mo_task_selectivity{type=\"column_total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "filterout-{{ pod }}"
    }
   ]
  },
  {
   "title": "Read filter request",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(rate(mo_task_selectivity{type=\"readfilter_total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "req-{{ pod }}"
    }
   ]
  },
  {
   "title": "Block range request",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(rate(mo_task_selectivity{type=\"block_total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "req-{{ pod }}"
    }
   ]
  },
  {
   "title": "Column update request",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(rate(mo_task_selectivity{type=\"column_total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "req-{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Task Merge Transfer Page Length",
 "panels": [
  {
   "title": "Transfer Page Length",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_task_merge_transfer_page_size{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}