{
 "title": "Trace Collector duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"collect\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "collect"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_awake\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_awake"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_awake_discard\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_awake_discard"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_delay\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_delay"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_discard\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_discard"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"export\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "export"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"collect\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "collect"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_awake\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_awake"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_awake_discard\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_awake_discard"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_delay\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_delay"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_discard\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_discard"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"export\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "export"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"collect\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "collect"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_awake\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_awake"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_awake_discard\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_awake_discard"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_delay\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_delay"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_discard\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_discard"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"export\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "export"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"collect\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "collect"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_awake\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_awake"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_awake_discard\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_awake_discard"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_delay\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_delay"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"generate_discard\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "generate_discard"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_trace_collector_duration_seconds_bucket{type=\"export\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "export"
    }
   ]
  }
 ]
}