{
 "title": "Txn overview",
 "panels": [
  {
   "title": "Txn requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_txn_total{type=\"user\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "user-txn"
    },
    {
     "expr": "sum(rate(mo_txn_total{type=\"internal\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "internal-txn"
    },
    {
     "expr": "sum(rate(mo_txn_statement_total{type=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "statement"
    },
    {
     "expr": "sum(rate(mo_txn_statement_total{type=\"retry\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "statement-retry"
    },
    {
     "expr": "sum(rate(mo_txn_lock_total{type=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "lock"
    },
    {
     "expr": "sum(rate(mo_txn_lock_total{type=\"local\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "local-lock"
    },
    {
     "expr": "sum(rate(mo_txn_lock_total{type=\"remote\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "remote-lock"
    }
   ]
  },
  {
   "title": "Commit requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_txn_commit_total{type=\"cn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "cn"
    },
    {
     "expr": "sum(rate(mo_txn_commit_total{type=\"tn-receive\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "tn-receive"
    },
    {
     "expr": "sum(rate(mo_txn_commit_total{type=\"tn-handle\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "tn-handle"
    }
   ]
  },
  {
   "title": "Rollback requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_txn_rollback_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Txn Queue Status",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_txn_queue_size{type=\"active\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(mo_txn_queue_size{type=\"wait-active\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "wait-active"
    },
    {
     "expr": "sum(mo_txn_queue_size{type=\"commit\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(mo_txn_queue_size{type=\"lock-rpc\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "lock-rpc"
    }
   ]
  }
 ]
}
{
 "title": "Txn create duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_life_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "life"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-active"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "determine-snapshot"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_life_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "life"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-active"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "determine-snapshot"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_life_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "life"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-active"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "determine-snapshot"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_life_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "life"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-active"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "determine-snapshot"
    }
   ]
  }
 ]
}
{
 "title": "Txn CN commit duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "response"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "logtail-applied"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tn"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "response"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "logtail-applied"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tn"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "response"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "logtail-applied"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tn"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "response"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "logtail-applied"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tn"
    }
   ]
  }
 ]
}
{
 "title": "Txn lock duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-total"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire-wait\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-wait"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-total"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-get-lock\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-get-lock"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-total"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-total"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire-wait\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-wait"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-total"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-get-lock\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-get-lock"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-total"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-total"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire-wait\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-wait"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-total"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-get-lock\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-get-lock"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-total"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-total"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire-wait\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-wait"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-total"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-get-lock\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-get-lock"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-total"
    }
   ]
  }
 ]
}
{
 "title": "Txn unlock tables",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_unlock_table_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tables"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_unlock_table_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tables"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_unlock_table_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tables"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_unlock_table_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tables"
    }
   ]
  }
 ]
}
{
 "title": "Txn lock waiters",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_lock_waiters_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "waiters"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_lock_waiters_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "waiters"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_lock_waiters_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "waiters"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_lock_waiters_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "waiters"
    }
   ]
  }
 ]
}
{
 "title": "Txn statement duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute-latency"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "build-plan"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compile\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compile"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute-latency"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "build-plan"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compile\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compile"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute-latency"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "build-plan"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compile\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compile"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute-latency"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "build-plan"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compile\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compile"
    }
   ]
  }
 ]
}
{
 "title": "Txn statements count",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_life_statements_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "statements/txn"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_life_statements_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "statements/txn"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_life_statements_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "statements/txn"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_life_statements_total_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "statements/txn"
    }
   ]
  }
 ]
}
{
 "title": "Txn table ranges",
 "panels": [
  {
   "title": "Txn table ranges duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_ranges_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_ranges_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_ranges_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_ranges_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "Txn table ranges count",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_ranges_duration_size_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_ranges_duration_size_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_ranges_duration_size_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_ranges_duration_size_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Txn reader duration",
 "panels": [
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-reader"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"merge-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "merge-reader"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-merge-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-merge-reader"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-reader"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"merge-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "merge-reader"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-merge-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-merge-reader"
    }
   ]
  },
  {
   "title": "P95.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.950000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-reader"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"merge-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "merge-reader"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-merge-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-merge-reader"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-reader"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"merge-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "merge-reader"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-merge-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-merge-reader"
    }
   ]
  }
 ]
}
{
 "title": "Txn MPool",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"new\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "new"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"alloc\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "alloc"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"free\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "free"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"delete\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"new\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "new"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"alloc\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "alloc"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"free\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "free"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"delete\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"new\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "new"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"alloc\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "alloc"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"free\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "free"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"delete\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"new\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "new"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"alloc\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "alloc"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"free\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "free"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"delete\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "delete"
    }
   ]
  }
 ]
}
{
 "title": "txn on prepare wal duration",
 "panels": [
  {
   "title": "txn on prepare wal duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "txn handle commit but before txn.commit duration",
 "panels": [
  {
   "title": "txn handle commit but before txn.commit duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"before_txn_commit\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"before_txn_commit\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"before_txn_commit\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"before_txn_commit\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "txn dequeue prepared duration",
 "panels": [
  {
   "title": "txn dequeue prepared duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_prepared\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_prepared\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_prepared\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_prepared\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "txn dequeue preparing duration",
 "panels": [
  {
   "title": "txn dequeue preparing duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_preparing\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_preparing\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_preparing\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_preparing\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Txn Ranges Loaded Object Meta",
 "panels": [
  {
   "title": "Txn Ranges Loaded Object Meta",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mo_txn_ranges_loaded_object_meta_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (pod, type)",
     "legendFormat": "{{ pod-type }}"
    }
   ]
  }
 ]
}
{
 "title": "Show Accounts Duration",
 "panels": [
  {
   "title": "Show Accounts Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_show_accounts_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_show_accounts_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_show_accounts_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_show_accounts_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Quantity of Object Location The CN Have Committed to TN",
 "panels": [
  {
   "title": "meta location",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_txn_cn_committed_location_quantity_size{type=\"meta_location\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "delta location",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_txn_cn_committed_location_quantity_size{type=\"delta_location\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixone_cloud_cluster=~\"$cluster\", pod=~\"$pod\"})"
    }
   ]
  }
 ]
}