{
 "title": "Memory Status",
 "panels": [
  {
   "title": "Live Objects",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_heap_objects_objects{namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Free and ready to return system",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_heap_free_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Dead objects and not marked free live objects",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_heap_objects_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Released to system",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_heap_released_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Heap Allocation Bytes/s",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_heap_allocs_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Heap Free Bytes/s",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_heap_frees_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Heap Allocation Object/s",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_heap_allocs_objects_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Heap Free Object/s",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_heap_frees_objects_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Allocation bytes size",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(go_gc_heap_allocs_by_size_bytes_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(go_gc_heap_allocs_by_size_bytes_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(go_gc_heap_allocs_by_size_bytes_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P95.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(go_gc_heap_allocs_by_size_bytes_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Go GC Status",
 "panels": [
  {
   "title": "STW duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(go_gc_pauses_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "{{ pod }}(P80.00%)"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(go_gc_pauses_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "{{ pod }}(P90.00%)"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(go_gc_pauses_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "{{ pod }}(P95.00%)"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(go_gc_pauses_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "{{ pod }}(P99.00%)"
    }
   ]
  }
 ]
}
{
 "title": "Goroutine Status",
 "panels": [
  {
   "title": "Goroutine count",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Schedule latency duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(go_sched_latencies_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "{{ pod }}(P80.00%)"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(go_sched_latencies_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "{{ pod }}(P90.00%)"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(go_sched_latencies_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "{{ pod }}(P95.00%)"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(go_sched_latencies_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "{{ pod }}(P99.00%)"
    }
   ]
  }
 ]
}