{
 "title": "Txn overview",
 "panels": [
  {
   "title": "Txn requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_txn_total{type=\"user\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "user-txn"
    },
    {
     "expr": "sum(rate(mo_txn_total{type=\"internal\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "internal-txn"
    },
    {
     "expr": "sum(rate(mo_txn_total{type=\"leak\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "leak"
    },
    {
     "expr": "sum(rate(mo_txn_statement_total{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "statement"
    },
    {
     "expr": "sum(rate(mo_txn_statement_total{type=\"retry\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "statement-retry"
    },
    {
     "expr": "sum(rate(mo_txn_lock_total{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "lock"
    },
    {
     "expr": "sum(rate(mo_txn_lock_total{type=\"local\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "local-lock"
    },
    {
     "expr": "sum(rate(mo_txn_lock_total{type=\"remote\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "remote-lock"
    }
   ]
  },
  {
   "title": "Commit requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_txn_commit_total{type=\"cn\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "cn"
    },
    {
     "expr": "sum(rate(mo_txn_commit_total{type=\"tn-receive\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "tn-receive"
    },
    {
     "expr": "sum(rate(mo_txn_commit_total{type=\"tn-handle\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "tn-handle"
    }
   ]
  },
  {
   "title": "Rollback requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_txn_rollback_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Txn Queue Status",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_txn_queue_size{type=\"active\",namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(mo_txn_queue_size{type=\"wait-active\",namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "wait-active"
    },
    {
     "expr": "sum(mo_txn_queue_size{type=\"commit\",namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(mo_txn_queue_size{type=\"lock-rpc\",namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "lock-rpc"
    }
   ]
  }
 ]
}
{
 "title": "Txn create duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_life_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "life"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-active"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "determine-snapshot"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_life_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "life"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-active"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "determine-snapshot"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_life_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "life"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-active"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "determine-snapshot"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_life_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "life"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-active"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "determine-snapshot"
    }
   ]
  }
 ]
}
{
 "title": "Txn CN commit duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "response"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "logtail-applied"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tn"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "response"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "logtail-applied"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tn"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "response"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "logtail-applied"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tn"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "response"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "logtail-applied"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tn"
    }
   ]
  }
 ]
}
{
 "title": "Txn lock duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-total"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire-wait\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-wait"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-total"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-get-lock\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-get-lock"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-total"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"worker-handle\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "worker-handle"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-total"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire-wait\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-wait"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-total"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-get-lock\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-get-lock"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-total"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"worker-handle\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "worker-handle"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-total"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire-wait\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-wait"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-total"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-get-lock\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-get-lock"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-total"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"worker-handle\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "worker-handle"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-total"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire-wait\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "lock-wait"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-total"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-get-lock\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-get-lock"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"btree-total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "unlock-btree-total"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_unlock_duration_seconds_bucket{type=\"worker-handle\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "worker-handle"
    }
   ]
  }
 ]
}
{
 "title": "Txn unlock tables",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_unlock_table_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tables"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_unlock_table_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tables"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_unlock_table_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tables"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_unlock_table_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tables"
    }
   ]
  }
 ]
}
{
 "title": "Txn lock waiters",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_lock_waiters_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "waiters"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_lock_waiters_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "waiters"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_lock_waiters_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "waiters"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_lock_waiters_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "waiters"
    }
   ]
  }
 ]
}
{
 "title": "Txn statement duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute-latency"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "build-plan"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compile\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compile"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"scan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "scan"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"external-scan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "external-scan"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"insert-s3\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "insert-s3"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "stats"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"resolve\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "resolve"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"resolve-udf\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "resolve-udf"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-stats"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-info-from-zonemap\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-info-from-zonemap"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-stats-info-map\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-stats-info-map"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"nodes\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "nodes"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compileScope\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compileScope"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compileQuery\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compileQuery"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compilePlanScope\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compilePlanScope"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildPlan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildPlan"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildSelect\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildSelect"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildInsert\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildInsert"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildExplain\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildExplain"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildReplace\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildReplace"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildUpdate\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildUpdate"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildDelete\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildDelete"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildLoad\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildLoad"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute-latency"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "build-plan"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compile\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compile"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"scan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "scan"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"external-scan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "external-scan"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"insert-s3\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "insert-s3"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "stats"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"resolve\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "resolve"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"resolve-udf\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "resolve-udf"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-stats"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-info-from-zonemap\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-info-from-zonemap"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-stats-info-map\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-stats-info-map"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"nodes\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "nodes"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compileScope\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compileScope"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compileQuery\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compileQuery"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compilePlanScope\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compilePlanScope"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildPlan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildPlan"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildSelect\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildSelect"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildInsert\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildInsert"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildExplain\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildExplain"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildReplace\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildReplace"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildUpdate\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildUpdate"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildDelete\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildDelete"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildLoad\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildLoad"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute-latency"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "build-plan"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compile\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compile"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"scan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "scan"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"external-scan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "external-scan"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"insert-s3\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "insert-s3"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "stats"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"resolve\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "resolve"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"resolve-udf\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "resolve-udf"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-stats"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-info-from-zonemap\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-info-from-zonemap"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-stats-info-map\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-stats-info-map"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"nodes\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "nodes"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compileScope\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compileScope"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compileQuery\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compileQuery"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compilePlanScope\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compilePlanScope"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildPlan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildPlan"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildSelect\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildSelect"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildInsert\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildInsert"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildExplain\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildExplain"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildReplace\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildReplace"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildUpdate\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildUpdate"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildDelete\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildDelete"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildLoad\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildLoad"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "execute-latency"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "build-plan"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compile\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compile"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"scan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "scan"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"external-scan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "external-scan"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"insert-s3\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "insert-s3"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "stats"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"resolve\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "resolve"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"resolve-udf\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "resolve-udf"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-stats"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-info-from-zonemap\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-info-from-zonemap"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"update-stats-info-map\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-stats-info-map"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"nodes\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "nodes"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compileScope\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compileScope"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compileQuery\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compileQuery"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"compilePlanScope\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "compilePlanScope"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildPlan\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildPlan"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildSelect\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildSelect"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildInsert\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildInsert"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildExplain\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildExplain"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildReplace\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildReplace"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildUpdate\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildUpdate"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildDelete\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildDelete"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"BuildLoad\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "BuildLoad"
    }
   ]
  }
 ]
}
{
 "title": "Txn statements count",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_life_statements_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "statements/txn"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_life_statements_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "statements/txn"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_life_statements_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "statements/txn"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_life_statements_total_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "statements/txn"
    }
   ]
  }
 ]
}
{
 "title": "Txn table ranges",
 "panels": [
  {
   "title": "Txn table ranges duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_ranges_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_ranges_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_ranges_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_ranges_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Txn check pk dup",
 "panels": [
  {
   "title": "Txn check pk dup duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_check_pk_dup_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_check_pk_dup_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_check_pk_dup_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_check_pk_dup_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Txn reader duration",
 "panels": [
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-reader"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"merge-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "merge-reader"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-merge-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-merge-reader"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-reader"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"merge-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "merge-reader"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-merge-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-merge-reader"
    }
   ]
  },
  {
   "title": "P95.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.950000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-reader"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"merge-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "merge-reader"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-merge-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-merge-reader"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-reader"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"merge-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "merge-reader"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_reader_duration_seconds_bucket{type=\"block-merge-reader\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "block-merge-reader"
    }
   ]
  }
 ]
}
{
 "title": "Txn MPool",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"new\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "new"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"alloc\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "alloc"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"free\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "free"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"delete\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"new\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "new"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"alloc\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "alloc"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"free\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "free"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"delete\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"new\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "new"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"alloc\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "alloc"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"free\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "free"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"delete\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"new\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "new"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"alloc\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "alloc"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"free\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "free"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_mpool_duration_seconds_bucket{type=\"delete\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "delete"
    }
   ]
  }
 ]
}
{
 "title": "txn on prepare wal duration",
 "panels": [
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_prepare_wal\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "prepare wal"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_end_prepare\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "end prepare"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_flush_queue\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "enqueue flush"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_prepare_wal\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "prepare wal"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_end_prepare\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "end prepare"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_flush_queue\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "enqueue flush"
    }
   ]
  },
  {
   "title": "P95.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.950000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_prepare_wal\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "prepare wal"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_end_prepare\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "end prepare"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_flush_queue\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "enqueue flush"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_prepare_wal\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "prepare wal"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_end_prepare\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "end prepare"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"on_prepare_wal_flush_queue\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "enqueue flush"
    }
   ]
  }
 ]
}
{
 "title": "txn handle commit but before txn.commit duration",
 "panels": [
  {
   "title": "txn handle commit but before txn.commit duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"before_txn_commit\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"before_txn_commit\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"before_txn_commit\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"before_txn_commit\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "txn dequeue prepared duration",
 "panels": [
  {
   "title": "txn dequeue prepared duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_prepared\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_prepared\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_prepared\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_prepared\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "txn dequeue preparing duration",
 "panels": [
  {
   "title": "txn dequeue preparing duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_preparing\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_preparing\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_preparing\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_tn_side_duration_seconds_bucket{step=\"dequeue_preparing\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Txn Ranges Loaded Object Meta",
 "panels": [
  {
   "title": "Txn Ranges Loaded Object Meta",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mo_txn_ranges_loaded_object_meta_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod, type)",
     "legendFormat": "{{ pod-type }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn Fast Ranges Selectivity",
 "panels": [
  {
   "title": "fast ranges block selectivity",
   "type": "graph",
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"fast_block_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"fast_block_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"fast_block_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"fast_block_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "fast ranges zone map selectivity",
   "type": "graph",
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"fast_zm_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"fast_zm_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"fast_zm_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"fast_zm_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "fast ranges result len",
   "type": "graph",
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_ranges_duration_size_bucket{type=\"fast_ranges_len\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_ranges_duration_size_bucket{type=\"fast_ranges_len\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_ranges_duration_size_bucket{type=\"fast_ranges_len\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_ranges_duration_size_bucket{type=\"fast_ranges_len\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Txn Ranges Selectivity",
 "panels": [
  {
   "title": "ranges block selectivity",
   "type": "graph",
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"block_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"block_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"block_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_ranges_selectivity_percentage_bucket{type=\"block_selectivity\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "ranges result len",
   "type": "graph",
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_ranges_duration_size_bucket{type=\"ranges_len\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_ranges_duration_size_bucket{type=\"ranges_len\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_ranges_duration_size_bucket{type=\"ranges_len\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_ranges_duration_size_bucket{type=\"ranges_len\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Show Accounts Duration",
 "panels": [
  {
   "title": "Show Accounts Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_show_accounts_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_show_accounts_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_show_accounts_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_show_accounts_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Quantity of Object Location The CN Have Committed to TN",
 "panels": [
  {
   "title": "meta location",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_txn_cn_committed_location_quantity_size{type=\"meta_location\",namespace=~\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "delta location",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_txn_cn_committed_location_quantity_size{type=\"delta_location\",namespace=~\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  }
 ]
}