{
 "title": "Frontend overview",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"created\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "created"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"establish\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "establish"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"upgradeTLS\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "upgradeTLS"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"authenticate\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "authenticate"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-tenant\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-tenant"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-user\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-user"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-role\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-role"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-dbname\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-dbname"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"init-global-sys-var\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-global-sys-var"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"created\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "created"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"establish\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "establish"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"upgradeTLS\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "upgradeTLS"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"authenticate\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "authenticate"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-tenant\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-tenant"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-user\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-user"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-role\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-role"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-dbname\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-dbname"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"init-global-sys-var\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-global-sys-var"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"created\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "created"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"establish\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "establish"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"upgradeTLS\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "upgradeTLS"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"authenticate\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "authenticate"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-tenant\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-tenant"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-user\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-user"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-role\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-role"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-dbname\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-dbname"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"init-global-sys-var\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-global-sys-var"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"created\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "created"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"establish\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "establish"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"upgradeTLS\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "upgradeTLS"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"authenticate\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "authenticate"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-tenant\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-tenant"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-user\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-user"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-role\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-role"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-dbname\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-dbname"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"init-global-sys-var\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-global-sys-var"
    }
   ]
  }
 ]
}