{
 "title": "Logtail overview",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_append_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "append"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-latency"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"network\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-network"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-latency"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify-latency"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-commit-apply"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_append_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "append"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-latency"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"network\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-network"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-latency"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify-latency"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-commit-apply"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_append_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "append"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-latency"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"network\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-network"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-latency"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify-latency"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-commit-apply"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_append_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "append"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-latency"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"network\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-network"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-latency"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify-latency\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify-latency"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-commit-apply"
    }
   ]
  }
 ]
}
{
 "title": "Logtail Queue Status",
 "panels": [
  {
   "title": "CN Received status",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_logtail_received_total{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}: total"
    },
    {
     "expr": "sum(rate(mo_logtail_received_total{type=\"subscribe\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}: subscribe"
    },
    {
     "expr": "sum(rate(mo_logtail_received_total{type=\"unsubscribe\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}: unsubscribe"
    },
    {
     "expr": "sum(rate(mo_logtail_received_total{type=\"update\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}: update"
    },
    {
     "expr": "sum(rate(mo_logtail_received_total{type=\"heartbeat\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}: heartbeat"
    }
   ]
  },
  {
   "title": "Queue status",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_logtail_queue_size{type=\"send\",namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "send"
    },
    {
     "expr": "sum(mo_logtail_queue_size{type=\"receive\",namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(mo_logtail_queue_size{type=\"apply\",namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "apply"
    }
   ]
  },
  {
   "title": "Checkpoint logtail",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_logtail_load_checkpoint_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Logtail size",
 "panels": [
  {
   "title": "Logtail size",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_bytes_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_bytes_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_bytes_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_bytes_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Logtail load checkpoint",
 "panels": [
  {
   "title": "Logtail load checkpoint",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_load_checkpoint_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_load_checkpoint_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_load_checkpoint_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_load_checkpoint_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Logtail collect duration",
 "panels": [
  {
   "title": "collect duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_collect_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_collect_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_collect_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_collect_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "logtail subscription the tn have received",
 "panels": [
  {
   "title": "logtail subscription average increase",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mo_logtail_subscription_request_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "logtail subscription average increase, sensitive",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mo_logtail_subscription_request_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}