{
 "title": "FileService read overview",
 "panels": [
  {
   "title": "S3 Read requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_read_total{type=\"s3\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Mem Read requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_read_total{type=\"hit-mem\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Disk Read requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_read_total{type=\"hit-disk\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Remote Read requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_read_total{type=\"hit-remote\"}[$interval]))"
    }
   ]
  }
 ]
}
{
 "title": "FileService write overview",
 "panels": [
  {
   "title": "S3 Write requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_write_total{type=\"s3\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Local Write requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_write_total{type=\"local\"}[$interval]))"
    }
   ]
  }
 ]
}
{
 "title": "FileService S3 read duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_io_duration_seconds_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_io_duration_seconds_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_io_duration_seconds_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_io_duration_seconds_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "FileService S3 read duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_io_duration_seconds_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_io_duration_seconds_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_io_duration_seconds_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_io_duration_seconds_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "FileService local read duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_local_io_duration_seconds_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_local_io_duration_seconds_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_local_io_duration_seconds_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_local_io_duration_seconds_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "FileService local read duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_local_io_duration_seconds_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_local_io_duration_seconds_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_local_io_duration_seconds_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_local_io_duration_seconds_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "FileService S3 read size",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "FileService S3 write size",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "FileService local read size",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"read\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "FileService local write size",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"write\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "FileService S3 connection status",
 "panels": [
  {
   "title": "Connect",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_s3_conn_duration_seconds_count{type=\"connect\"}[$interval]))"
    }
   ]
  },
  {
   "title": "DNS Resolve",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_s3_conn_duration_seconds_count{type=\"dns-resolve\"}[$interval]))"
    }
   ]
  }
 ]
}
{
 "title": "FileService connect to S3",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"connect\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"connect\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"connect\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"connect\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "FileService get S3 connection",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"get-conn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"get-conn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"get-conn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"get-conn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "FileService resolve S3 dns",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"dns-resolve\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"dns-resolve\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"dns-resolve\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"dns-resolve\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "FileService S3 connection tls handshake",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"tls-handshake\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"tls-handshake\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"tls-handshake\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"tls-handshake\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}