{
 "title": "RPC overview",
 "panels": [
  {
   "title": "RPC Network Input",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mo_rpc_network_bytes{type=\"input\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "RPC Network Output",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mo_rpc_network_bytes{type=\"output\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "RPC Client Create",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_rpc_client_create_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Connection pool",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_rpc_backend_pool_size{namespace=~\"$namespace\", pod=~\"$pod\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Sending queue",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_rpc_sending_queue_size{namespace=~\"$namespace\", pod=~\"$pod\"}) by (name, side)",
     "legendFormat": "{{ name }}({{ side }})"
    }
   ]
  },
  {
   "title": "Write Batch Size",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_rpc_sending_batch_size{namespace=~\"$namespace\", pod=~\"$pod\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Server sessions",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_rpc_server_session_size{namespace=~\"$namespace\", pod=~\"$pod\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}
{
 "title": "Connection Status",
 "panels": [
  {
   "title": "Create",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_rpc_backend_create_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Close",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_rpc_backend_close_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Reconnect Total",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_rpc_backend_connect_total{type=\"total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Reconnect Failed",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_rpc_backend_connect_total{type=\"failed\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}
{
 "title": "RPC connection duration",
 "panels": [
  {
   "title": "Connect duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_rpc_backend_connect_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P50.00%)"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_rpc_backend_connect_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P80.00%)"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_rpc_backend_connect_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P90.00%)"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_rpc_backend_connect_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P99.00%)"
    }
   ]
  }
 ]
}
{
 "title": "RPC write duration",
 "panels": [
  {
   "title": "Client-side Write To Network Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_rpc_write_duration_seconds_bucket{side=\"client\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P50.00%)"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_rpc_write_duration_seconds_bucket{side=\"client\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P80.00%)"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_rpc_write_duration_seconds_bucket{side=\"client\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P90.00%)"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_rpc_write_duration_seconds_bucket{side=\"client\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P99.00%)"
    }
   ]
  },
  {
   "title": "Client-side Write Latency Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_rpc_write_latency_duration_seconds_bucket{side=\"client\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P50.00%)"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_rpc_write_latency_duration_seconds_bucket{side=\"client\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P80.00%)"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_rpc_write_latency_duration_seconds_bucket{side=\"client\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P90.00%)"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_rpc_write_latency_duration_seconds_bucket{side=\"client\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P99.00%)"
    }
   ]
  },
  {
   "title": "Server-side Write To Network Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_rpc_write_duration_seconds_bucket{side=\"server\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P50.00%)"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_rpc_write_duration_seconds_bucket{side=\"server\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P80.00%)"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_rpc_write_duration_seconds_bucket{side=\"server\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P90.00%)"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_rpc_write_duration_seconds_bucket{side=\"server\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P99.00%)"
    }
   ]
  },
  {
   "title": "Server-side Write Latency Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_rpc_write_latency_duration_seconds_bucket{side=\"server\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P50.00%)"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_rpc_write_latency_duration_seconds_bucket{side=\"server\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P80.00%)"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_rpc_write_latency_duration_seconds_bucket{side=\"server\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P90.00%)"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_rpc_write_latency_duration_seconds_bucket{side=\"server\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P99.00%)"
    }
   ]
  }
 ]
}
{
 "title": "Request done Duration",
 "panels": [
  {
   "title": "Request done Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_rpc_backend_done_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P50.00%)"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_rpc_backend_done_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P80.00%)"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_rpc_backend_done_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P90.00%)"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_rpc_backend_done_duration_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, name))",
     "legendFormat": "{{ name }}(P99.00%)"
    }
   ]
  }
 ]
}