{
 "title": "Flush Table Tail",
 "panels": [
  {
   "title": "Flush table tail Count",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum by (pod) (increase(mo_task_short_duration_seconds_count{type=\"flush_table_tail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Flush table tail Duration",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"flush_table_tail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"flush_table_tail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"flush_table_tail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"flush_table_tail\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Flush table deletes count",
   "type": "timeseries",
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_hist_total_bucket{type=\"flush_deletes_count\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.700000, sum(rate(mo_task_hist_total_bucket{type=\"flush_deletes_count\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P70"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_hist_total_bucket{type=\"flush_deletes_count\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_hist_total_bucket{type=\"flush_deletes_count\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Flush table deletes file size",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_hist_bytes_bucket{type=\"flush_deletes_size\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.700000, sum(rate(mo_task_hist_bytes_bucket{type=\"flush_deletes_size\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P70"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_hist_bytes_bucket{type=\"flush_deletes_size\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_hist_bytes_bucket{type=\"flush_deletes_size\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P90"
    }
   ]
  }
 ]
}
{
 "title": "Merge",
 "panels": [
  {
   "title": "Merge Count",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum by (pod) (increase(mo_task_execute_results_total{type=\"merged_block\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Block Count"
    },
    {
     "expr": "sum by (pod) (increase(mo_task_scheduled_by_total{type=\"merge\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Schedule Count"
    }
   ]
  },
  {
   "title": "Merge Batch Size",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(mo_task_execute_results_total{type=\"merged_size\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Size"
    }
   ]
  }
 ]
}
{
 "title": "Checkpoint",
 "panels": [
  {
   "title": "Checkpoint Entry Pending",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_long_duration_seconds_bucket{type=\"ckp_entry_pending\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_long_duration_seconds_bucket{type=\"ckp_entry_pending\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_long_duration_seconds_bucket{type=\"ckp_entry_pending\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_long_duration_seconds_bucket{type=\"ckp_entry_pending\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}
{
 "title": "Read Selectivity",
 "panels": [
  {
   "title": "Read filter rate",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(mo_task_selectivity{type=\"readfilter_hit\",namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod) / on(pod) sum(mo_task_selectivity{type=\"readfilter_total\",namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "filterout-{{ pod }}"
    }
   ]
  },
  {
   "title": "Block range filter rate",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(mo_task_selectivity{type=\"block_hit\",namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod) / on(pod) sum(mo_task_selectivity{type=\"block_total\",namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "filterout-{{ pod }}"
    }
   ]
  },
  {
   "title": "Column update filter rate",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(mo_task_selectivity{type=\"column_hit\",namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod) / on(pod) sum(mo_task_selectivity{type=\"column_total\",namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "filterout-{{ pod }}"
    }
   ]
  },
  {
   "title": "Read filter request",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(rate(mo_task_selectivity{type=\"readfilter_total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "req-{{ pod }}"
    }
   ]
  },
  {
   "title": "Block range request",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(rate(mo_task_selectivity{type=\"block_total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "req-{{ pod }}"
    }
   ]
  },
  {
   "title": "Column update request",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(rate(mo_task_selectivity{type=\"column_total\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "req-{{ pod }}"
    }
   ]
  },
  {
   "title": "Iterate deletes rows count per block",
   "type": "timeseries",
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_hist_total_bucket{type=\"load_mem_deletes_per_block\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.700000, sum(rate(mo_task_hist_total_bucket{type=\"load_mem_deletes_per_block\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P70"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_hist_total_bucket{type=\"load_mem_deletes_per_block\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_hist_total_bucket{type=\"load_mem_deletes_per_block\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "P90"
    }
   ]
  }
 ]
}
{
 "title": "Task Merge Transfer Page Length",
 "panels": [
  {
   "title": "Transfer Page Length",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_task_merge_transfer_page_size{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Storage Usage Overview",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"gckp_collect_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "gckp_collect_usage"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"ickp_collect_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "ickp_collect_usage"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"handle_usage_request\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "handle_usage_request"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_get_table_stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_get_table_stats"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_get_storage_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_get_storage_usage"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_total_duration\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_total_duration"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"gckp_collect_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "gckp_collect_usage"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"ickp_collect_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "ickp_collect_usage"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"handle_usage_request\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "handle_usage_request"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_get_table_stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_get_table_stats"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_get_storage_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_get_storage_usage"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_total_duration\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_total_duration"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"gckp_collect_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "gckp_collect_usage"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"ickp_collect_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "ickp_collect_usage"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"handle_usage_request\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "handle_usage_request"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_get_table_stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_get_table_stats"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_get_storage_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_get_storage_usage"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_total_duration\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_total_duration"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"gckp_collect_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "gckp_collect_usage"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"ickp_collect_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "ickp_collect_usage"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"handle_usage_request\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "handle_usage_request"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_get_table_stats\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_get_table_stats"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_get_storage_usage\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_get_storage_usage"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_task_short_duration_seconds_bucket{type=\"show_accounts_total_duration\",namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "show_accounts_total_duration"
    }
   ]
  },
  {
   "title": "tn storage usage cache mem used",
   "type": "graph",
   "yaxes": [
    { "format": "mb" }
   ],
   "targets": [
    {
     "expr": "sum(mo_task_storage_usage_cache_size{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "cache mem used"
    }
   ]
  }
 ]
}