{
 "title": "Txn overview",
 "panels": [
  {
   "title": "Txn requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_txn_total[$interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Statement requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_txn_statement_total[$interval]))"
    }
   ]
  },
  {
   "title": "Commit requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_txn_commit_total) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Rollback requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_txn_rollback_total) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn life",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_life_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_life_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_life_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_life_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn create",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"total\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn determine snapshot",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"determine-snapshot\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn wait active",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_create_duration_seconds_bucket{type=\"wait-active\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn Queue Status",
 "panels": [
  {
   "title": "Txn Active Queue",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_txn_queue_size{type=\"active\"})"
    }
   ]
  },
  {
   "title": "Txn Wait Active Queue",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_txn_queue_size{type=\"wait-active\"})"
    }
   ]
  },
  {
   "title": "TN Commit Queue",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_txn_queue_size{type=\"commit\"})"
    }
   ]
  }
 ]
}
{
 "title": "Txn CN Commit",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn CN Send Commit Request",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-send\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn CN receive commit response",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-resp\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn CN wait commit logtail",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn TN commit",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"tn\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn build plan",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"build-plan\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn execute statement",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_statement_duration_seconds_bucket{type=\"execute\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn Acquire Lock",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"acquire\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn Hold Lock",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"hold\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"hold\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"hold\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_lock_duration_seconds_bucket{type=\"hold\"}[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn Release Lock",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_unlock_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_unlock_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_unlock_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_unlock_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Txn execute table ranges",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_ranges_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_ranges_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_ranges_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_ranges_duration_seconds_bucket[$interval])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}