name: Get Release Upload URL

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to get upload URL for'
        required: true

jobs:
  get_upload_url:
    runs-on: ubuntu-latest
    steps:
    - name: Get Upload URL
      id: get_upload_url
      run: |
        tag_name="${{ github.event.inputs.tag_name }}"
        upload_url=$(curl -s -H "Authorization: token ${{ secrets.TOKEN_ACTION }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/repos/${{ github.repository }}/releases/tags/$tag_name" \
                        | jq -r '.upload_url')
        echo "::set-output name=upload_url::$upload_url"

    - name: Output Upload URL
      run: echo "Release upload URL is ${{ steps.get_upload_url.outputs.upload_url }}"
