name: Get Latest Release Tag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-release-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release
        id: get-latest-release
        run: |
          LATEST_RELEASE_JSON=($(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/lcxznpy/asdf/releases/latest) | jq -r .tag_name)
          LATEST_RELEASE_TAG=$(echo $LATEST_RELEASE_JSON )
          echo "RELEASE_TAG=$LATEST_RELEASE_TAG" >> $GITHUB_ENV

      - name: Use the release tag
        run: |
          echo "Using release tag $RELEASE_TAG"
