name: qaq test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run : |
          echo "qwer"
          
  auto-assign-to-project:
    if: github.event = "workflow_dispatch"
    name: echo
    uses: lcxznpy/asdf/.github/workflows/qaq/qaq.yaml@main
